config-version: 2

name: 'salesforce'
version: '0.0.1'

require-dbt-version: [">=0.18.0", "<0.19.0"]

models:
    salesforce:
        materialized: table
        intermediate:
            materialized: ephemeral